[platformio]
src_dir = .

[env:ch32v003]
platform = ch32v
board = ch32v003f4p6_evt_r0
framework = arduino
monitor_speed = 115200
; use OpenWCH core impelmetnation
board_build.core = openwch
; uncomment this to use USB bootloader upload via WCHISP
;upload_protocol = isp
